"""added add options and control accounts on residenttype

Revision ID: 0a8deafb90aa
Revises: 636e2bafa6f4
Create Date: 2024-09-04 20:33:44.188373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8deafb90aa'
down_revision = '636e2bafa6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residenttype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('add_post', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('add_event', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('add_announcement', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('control_accounts', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residenttype', schema=None) as batch_op:
        batch_op.drop_column('control_accounts')
        batch_op.drop_column('add_announcement')
        batch_op.drop_column('add_event')
        batch_op.drop_column('add_post')

    # ### end Alembic commands ###
