"""added nullable constraint on user_username in userdetails

Revision ID: 1f3a0584ba57
Revises: 0a8deafb90aa
Create Date: 2024-09-05 03:57:11.094901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1f3a0584ba57'
down_revision = '0a8deafb90aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userdetails', schema=None) as batch_op:
        batch_op.alter_column('user_username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
        batch_op.create_unique_constraint(None, ['user_username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userdetails', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('user_username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)

    # ### end Alembic commands ###
