"""empty message

Revision ID: 374b6ecd4c65
Revises: 
Create Date: 2024-09-14 01:40:04.840152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '374b6ecd4c65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    with op.batch_alter_table('brgystreets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    with op.batch_alter_table('residenttype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    with op.batch_alter_table('userdetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    with op.batch_alter_table('verifiedusers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_verified')

    with op.batch_alter_table('villages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('villages', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    with op.batch_alter_table('verifiedusers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_verified', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('date_created')

    with op.batch_alter_table('userdetails', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    with op.batch_alter_table('residenttype', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    with op.batch_alter_table('brgystreets', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('date_created')

    # ### end Alembic commands ###
