"""empty message

Revision ID: 4e997267439e
Revises: 9a7b5080ab24
Create Date: 2025-02-10 17:51:30.044919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e997267439e'
down_revision = '9a7b5080ab24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index('user_id', ['user_id'], unique=True)

    # ### end Alembic commands ###
