"""added selfie_column in userdetails

Revision ID: 636e2bafa6f4
Revises: 
Create Date: 2024-09-04 16:23:46.694200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636e2bafa6f4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userdetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selfie_photo_path', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userdetails', schema=None) as batch_op:
        batch_op.drop_column('selfie_photo_path')

    # ### end Alembic commands ###
