"""empty message

Revision ID: 810b3de5423f
Revises: 343b9c39f0cf
Create Date: 2025-03-09 01:07:52.854413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810b3de5423f'
down_revision = '343b9c39f0cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_constraint('announcements_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'posts', ['posts_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('announcements_ibfk_1', 'posts', ['posts_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
