"""empty message

Revision ID: 96902cd9cf04
Revises: dbd0e70045d0
Create Date: 2024-10-10 18:01:21.919309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96902cd9cf04'
down_revision = 'dbd0e70045d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formresponses', schema=None) as batch_op:
        batch_op.alter_column('form_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('formresponses', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('form_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###
