"""empty message

Revision ID: 9a7b5080ab24
Revises: 
Create Date: 2025-02-10 02:28:57.872696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a7b5080ab24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residenttype', schema=None) as batch_op:
        batch_op.alter_column('manage_request',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residenttype', schema=None) as batch_op:
        batch_op.alter_column('manage_request',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))

    # ### end Alembic commands ###
