"""empty message

Revision ID: dbd0e70045d0
Revises: 
Create Date: 2024-09-30 09:23:20.225439

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dbd0e70045d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formresponses', schema=None) as batch_op:
        batch_op.alter_column('form_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)

    with op.batch_alter_table('residenttype', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partial_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('residenttype', schema=None) as batch_op:
        batch_op.drop_column('partial_admin')

    with op.batch_alter_table('formresponses', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
        batch_op.alter_column('form_id',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###
