"""empty message

Revision ID: e172804256cb
Revises: f9e494bc62b6
Create Date: 2025-02-28 01:43:32.308384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e172804256cb'
down_revision = 'f9e494bc62b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userdetails', schema=None) as batch_op:
        batch_op.add_column(sa.Column('civil_status', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userdetails', schema=None) as batch_op:
        batch_op.drop_column('birthday')
        batch_op.drop_column('civil_status')

    # ### end Alembic commands ###
