"""empty message

Revision ID: e4f970ff8513
Revises: a93c809b0e5f
Create Date: 2025-03-07 16:22:01.224114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f970ff8513'
down_revision = 'a93c809b0e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventattendance', schema=None) as batch_op:
        batch_op.drop_constraint('eventattendance_ibfk_2', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventattendance', schema=None) as batch_op:
        batch_op.create_foreign_key('eventattendance_ibfk_2', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
