"""empty message

Revision ID: f28329135c54
Revises: 
Create Date: 2025-02-16 03:55:04.046244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28329135c54'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventattendance', schema=None) as batch_op:
        batch_op.drop_constraint('eventattendance_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint('events_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('formresponses', schema=None) as batch_op:
        batch_op.drop_constraint('formresponses_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_constraint('forms_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_constraint('incidents_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('postcomments', schema=None) as batch_op:
        batch_op.drop_constraint('postcomments_ibfk_2', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint('posts_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])

    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint('requests_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('requests_ibfk_1', 'verifiedusers', ['user_id'], ['user_id'])

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('posts_ibfk_1', 'verifiedusers', ['created_by'], ['user_id'])

    with op.batch_alter_table('postcomments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('postcomments_ibfk_2', 'verifiedusers', ['user_id'], ['user_id'])

    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('incidents_ibfk_1', 'verifiedusers', ['user_id'], ['user_id'])

    with op.batch_alter_table('forms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('forms_ibfk_1', 'verifiedusers', ['created_by'], ['user_id'])

    with op.batch_alter_table('formresponses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('formresponses_ibfk_2', 'verifiedusers', ['user_id'], ['user_id'])

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('events_ibfk_1', 'verifiedusers', ['created_by'], ['user_id'])

    with op.batch_alter_table('eventattendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('eventattendance_ibfk_2', 'verifiedusers', ['user_id'], ['user_id'])

    # ### end Alembic commands ###
