"""empty message

Revision ID: f9e494bc62b6
Revises: 926d9507294c
Create Date: 2025-02-27 22:46:25.310678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9e494bc62b6'
down_revision = '926d9507294c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verifiedusers', schema=None) as batch_op:
        batch_op.drop_constraint('verifiedusers_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['verified_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verifiedusers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('verifiedusers_ibfk_1', 'users', ['verified_by'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
